apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-lib
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies-lib
  template:
    metadata:
      labels:
        app: movies-lib
    spec:
      containers:
        - name: go-movies-lib
          image: tomaslingotti/movies-lib:0.0.3
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000