apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-lib
spec:
  replicas: 2
  selector:
    matchLabels:
      name: movies-lib
  template:
    metadata:
      labels:
        name: movies-lib
    spec:
      containers:
        - name: go-movies-lib
          image: tomaslingotti/movies-lib:0.0.3
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000